#!/usr/bin/env bash
# install.sh — the ONE idempotent installer for the LateShift Cloud infra tree.
#
# Replaces the pile of hand-run `install -m 755 ...` commands that let the
# installed tree drift from deploy/lateshift/ (the source of truth).
#
#   Usage:
#     tools/install.sh --dry-run          # show every difference, change nothing
#     tools/install.sh --dry-run -v       # ... plus a unified diff per file
#     tools/install.sh                    # apply (requires root)
#     tools/install.sh --only portal      # restrict to one group
#
#   Groups: gateway, bin, instance-bin, tools, portal, units, docs
#
# Properties:
#   * Idempotent — a second run is a no-op and prints "up to date".
#   * Content-addressed — a file is only touched when its bytes differ;
#     ownership/mode are corrected independently.
#   * Never touches runtime STATE: users.json, users/, archive/, secrets/,
#     portal.config.json, portal/static/, assets/. Those are listed in
#     PRESERVE below purely as documentation of what is deliberately untouched.
#   * Never touches PRODUCTION: t3code.service, port 3773, tailnet 443,
#     cloudflared, /home/dev/services/t3code-production. The only unit files it
#     writes are t3ws@.service (the per-WORKSPACE template — note the '@') and
#     lateshift-portal.service. The budget timer/service are gone (W2), and so
#     is the legacy t3code@.service template (replaced by t3ws@ in W5).
#   * Does NOT restart anything by itself. It runs `systemctl daemon-reload`
#     when a unit file changed and `caddy validate` when the Caddyfile changed,
#     then TELLS you which ops-broker action to run:
#       portal changed  -> ops deploy-portal {}       (self-heals w/ rollback)
#       gateway changed -> ops update-gateway {}
#       t3ws@.service   -> restart workspaces one at a time, canary first
#     Automatic restarts are deliberately out of scope: a bad portal deploy must
#     go through the broker's supervised rollback path, not through this script.
#
# SAFETY: the production instance is never referenced here. If you find yourself
# adding `t3code.service` (no '@') or port 3773/443 to this file, stop.

set -euo pipefail

SRC_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # deploy/lateshift
LSC="${LSC_ROOT_OVERRIDE:-/home/dev/services/lateshift}"
CADDY_DIR="${CADDY_DIR_OVERRIDE:-/etc/caddy}"
UNIT_DIR="${UNIT_DIR_OVERRIDE:-/etc/systemd/system}"

DRY_RUN=0
VERBOSE=0
ONLY=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run|-n) DRY_RUN=1; shift ;;
        --verbose|-v) VERBOSE=1; shift ;;
        --only) ONLY="${2:?--only needs a group}"; shift 2 ;;
        -h|--help) sed -n '2,36p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "install.sh: unknown argument '$1' (try --help)" >&2; exit 2 ;;
    esac
done

# Runtime state this script must NEVER write. Documentation + a live assertion
# that no MANIFEST entry accidentally targets one of them.
PRESERVE=(
    "${LSC}/registry.json"              # v2 registry (written only by lsw)
    "${LSC}/users.json"                 # legacy v1 registry, kept for migration
    "${LSC}/profiles.json"              # portal-owned GitHub avatar/name cache
    "${LSC}/pending.json"
    "${LSC}/workspaces"                 # v2 per-workspace base dirs
    "${LSC}/users"                      # legacy v1 base dirs
    "${LSC}/state"                      # rate-limit snapshots (lsw init owns it)
    "${LSC}/archive"
    "${LSC}/secrets"
    "${LSC}/secrets.env"
    "${LSC}/portal.config.json"
    "${LSC}/portal/static"
    "${LSC}/assets"
    "${LSC}/checkout"
    "${CADDY_DIR}/lsc-users.caddy"      # generated by render-gateway, not installed
)

# group | source (relative to deploy/lateshift) | destination | mode | owner:group
MANIFEST=(
    "gateway|gateway/Caddyfile|${CADDY_DIR}/Caddyfile|644|root:root"
    "gateway|gateway/render-gateway|${LSC}/bin/render-gateway|755|dev:dev"

    # W5 replaced run-instance.sh + t3user with run-workspace.sh + lsw. Both of
    # the old destinations are deliberately NOT cleaned up by this script: it
    # only ever writes files it owns. Remove them by hand once the legacy
    # t3code@ fleet is decommissioned (W8).
    "bin|run-workspace.sh|${LSC}/bin/run-workspace.sh|755|root:root"
    "bin|lsw|${LSC}/bin/lsw|755|root:root"

    "instance-bin|instance-bin/lsc-github-login|${LSC}/instance-bin/lsc-github-login|755|dev:dev"

    "tools|tools/apply-branding.sh|${LSC}/tools/apply-branding.sh|755|dev:dev"
    "tools|tools/update-from-upstream.sh|${LSC}/tools/update-from-upstream.sh|755|dev:dev"

    # Portal code. 644 (not the historical 664/775): these are read by node and
    # never executed directly, and group-write on dev-owned service code buys
    # nothing. portal/static/ and portal.config.json are deliberately absent.
    "portal|portal/package.json|${LSC}/portal/package.json|644|dev:dev"
    "portal|portal/server.mjs|${LSC}/portal/server.mjs|644|dev:dev"
    "portal|portal/views.mjs|${LSC}/portal/views.mjs|644|dev:dev"
    "portal|portal/lib/actions.mjs|${LSC}/portal/lib/actions.mjs|644|dev:dev"
    "portal|portal/lib/auth.mjs|${LSC}/portal/lib/auth.mjs|644|dev:dev"
    "portal|portal/lib/history.mjs|${LSC}/portal/lib/history.mjs|644|dev:dev"
    "portal|portal/lib/ops.mjs|${LSC}/portal/lib/ops.mjs|644|dev:dev"
    "portal|portal/lib/paths.mjs|${LSC}/portal/lib/paths.mjs|644|dev:dev"
    "portal|portal/lib/profiles.mjs|${LSC}/portal/lib/profiles.mjs|644|dev:dev"
    "portal|portal/lib/rateLimits.mjs|${LSC}/portal/lib/rateLimits.mjs|644|dev:dev"
    "portal|portal/lib/registry.mjs|${LSC}/portal/lib/registry.mjs|644|dev:dev"
    "portal|portal/lib/usage.mjs|${LSC}/portal/lib/usage.mjs|644|dev:dev"

    "units|lateshift-portal.service|${UNIT_DIR}/lateshift-portal.service|644|root:root"
    "units|t3ws@.service|${UNIT_DIR}/t3ws@.service|644|root:root"
    # /run/lsc must exist root-owned BEFORE the first t3ws@ unit starts, or the
    # first workspace account to start owns it and can impersonate the others.
    "units|tmpfiles-lsc.conf|/etc/tmpfiles.d/lsc.conf|644|root:root"

    "docs|README.md|${LSC}/README.md|644|root:root"
    "docs|README-isolation.md|${LSC}/README-isolation.md|644|root:root"
)

# Repo-only files: intentionally NOT installed. Listed so that a future reader
# does not "fix" the omission, and so --dry-run can account for every file in
# deploy/lateshift.
NOT_INSTALLED=(
    "gateway/README.md"        # developer docs
    "portal/README.md"         # developer docs
    "portal/test/w4-smoke.mjs" # test, run from a checkout
    "tools/t3client.mjs"       # local dev helper, run from a checkout
    "tools/install.sh"         # this script
)

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }

CHANGED_GROUPS=""
NCHANGE=0

note_group() { case " ${CHANGED_GROUPS} " in *" $1 "*) ;; *) CHANGED_GROUPS="${CHANGED_GROUPS} $1" ;; esac; }

# --- sanity ----------------------------------------------------------------
[[ -f "${SRC_ROOT}/lsw" ]] || { echo "install.sh: ${SRC_ROOT} does not look like deploy/lateshift" >&2; exit 1; }
if (( ! DRY_RUN )) && [[ "$(id -u)" != 0 ]]; then
    echo "install.sh: apply mode must run as root (use --dry-run otherwise)" >&2
    exit 1
fi
for entry in "${MANIFEST[@]}"; do
    IFS='|' read -r _g _s dest _m _o <<< "${entry}"
    for p in "${PRESERVE[@]}"; do
        [[ "${dest}" == "${p}" || "${dest}" == "${p}/"* ]] && {
            echo "install.sh: BUG - manifest entry targets preserved path ${dest}" >&2; exit 1; }
    done
done
# Every non-doc file in the source tree must be either installed or explicitly
# declared repo-only; this is what stops a new orphan (like the old
# portal/actions.mjs) from sitting unnoticed in the tree.
while IFS= read -r rel; do
    covered=0
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r _g s _d _m _o <<< "${entry}"
        [[ "${s}" == "${rel}" ]] && { covered=1; break; }
    done
    if (( ! covered )); then
        for n in "${NOT_INSTALLED[@]}"; do [[ "${n}" == "${rel}" ]] && { covered=1; break; }; done
    fi
    (( covered )) || { red "UNACCOUNTED source file: ${rel} (add it to MANIFEST or NOT_INSTALLED)"; NCHANGE=$((NCHANGE+1)); }
done < <(cd "${SRC_ROOT}" && find . -type f -printf '%P\n' | sort)

# --- walk the manifest ------------------------------------------------------
for entry in "${MANIFEST[@]}"; do
    IFS='|' read -r group src dest mode owner <<< "${entry}"
    [[ -n "${ONLY}" && "${ONLY}" != "${group}" ]] && continue
    abs="${SRC_ROOT}/${src}"
    [[ -f "${abs}" ]] || { red "MISSING SOURCE ${src}"; NCHANGE=$((NCHANGE+1)); continue; }

    content_differs=0
    meta_differs=0
    reason=""
    if [[ ! -e "${dest}" ]]; then
        content_differs=1; reason="new file"
    else
        cmp -s "${abs}" "${dest}" || { content_differs=1; reason="content differs"; }
        cur="$(stat -c '%a %U:%G' "${dest}")"
        [[ "${cur}" == "${mode} ${owner}" ]] || { meta_differs=1; reason="${reason:+${reason}, }mode/owner ${cur} -> ${mode} ${owner}"; }
    fi

    if (( content_differs || meta_differs )); then
        NCHANGE=$((NCHANGE+1)); note_group "${group}"
        yellow "CHANGE [${group}] ${src} -> ${dest}  (${reason})"
        if (( VERBOSE && content_differs )) && [[ -e "${dest}" ]]; then
            diff -u "${dest}" "${abs}" | sed 's/^/      /' || true
        fi
        if (( ! DRY_RUN )); then
            install -D -o "${owner%%:*}" -g "${owner##*:}" -m "${mode}" "${abs}" "${dest}"
            green "  installed"
        fi
    else
        (( VERBOSE )) && echo "ok     [${group}] ${dest}"
    fi
done

# --- post-actions -----------------------------------------------------------
echo
if (( NCHANGE == 0 )); then
    green "install.sh: everything up to date (${LSC}, ${CADDY_DIR}, ${UNIT_DIR})"
    exit 0
fi

if (( DRY_RUN )); then
    yellow "install.sh: --dry-run — ${NCHANGE} change(s) NOT applied."
else
    case " ${CHANGED_GROUPS} " in *" units "*)
        echo "systemctl daemon-reload (unit files changed)"
        systemctl daemon-reload ;;
    esac
    case " ${CHANGED_GROUPS} " in *" gateway "*)
        echo "caddy validate"
        caddy validate --config "${CADDY_DIR}/Caddyfile" --adapter caddyfile >/dev/null \
            || { red "caddy config INVALID — NOT reloading; fix ${CADDY_DIR}/Caddyfile"; exit 1; }
        green "  caddy config valid" ;;
    esac
fi

echo
echo "Follow-up actions you must run yourself (this script never restarts anything):"
for g in ${CHANGED_GROUPS}; do
    case "${g}" in
        portal)  echo "  portal  -> ops deploy-portal '{}'   (supervised, auto-rollback)" ;;
        gateway) echo "  gateway -> ops update-gateway '{}'  (re-render + reload caddy)" ;;
        units)   echo "  units   -> systemd-tmpfiles --create /etc/tmpfiles.d/lsc.conf, then" \
                      && echo "             restart affected WORKSPACES ONE AT A TIME, canary first:" \
                      && echo "               ops restart-instance '{\"name\":\"testuser\"}'" ;;
        bin|instance-bin|tools|docs) echo "  ${g}     -> no restart needed" ;;
    esac
done
exit 0
